### ISSUE TITLE
Can't insert product

### ISSUE THREAD

**Issue by serdarejepov** [reactioncommerce/reaction-admin#220]
I setup reactioncommerce development platform. Everything was installed successfully and all needed services are running. However I couldn't insert new product via admin panel. 

The errors:

1) 3f04a941e67ea87b2dcf595efea5792c1a821e3e.js?meteor_js_resource=true:1 Exception in delivering result of invoking 'products/updateProductField': TypeError: this.forceUpdate is not a function

2) Network error: Invariant Violation: 16 (see https://github.com/apollographql/invariant-packages)

And when I reload the page, products with no data has been added.

Could you help me or guide me on how to go in right way, please?

**Comment by loan-laux** [comment]
Hi @serdarejepov, `reaction-admin` is the last bit of RC 3 that's still in beta. One of the only things left to do is to update the product editor to use GraphQL instead of the old Meteor API. In the meantime, it won't work as is. Sorry about that!

You can track the progress of the new product editor in PR #188. No official ETA but I'd say it's pretty close to being merged. Maybe @mikemurray can comment on that?

**Comment by manueldelreal** [comment]
@gabry12 this is the issue that tracks what you reported earlier today.

**Comment by artcoded** [comment]
Ok thanks a lot @manueldelreal

**Comment by gabry12** [comment]
Ok thanks a lot @manueldelreal

**Comment by loan-laux** [comment]
Pretty sure this should be fixed now. @serdarejepov do you confirm?

**Comment by serdarejepov** [comment]
I will try... If still have error, then I will ask again

**Comment by ghost** [comment]
It still doesn't work. After I click on 'Create product', there's a spinning wheel at the top that runs forever. There are no buttons. When I edit the fields, I get the following error: `Match failed [400]`.

There's also an error in the console:

```
Exception in delivering result of invoking 'products/updateProductField':
TypeError: this.forceUpdate is not a function. (In 'this.forceUpdate()', 'this.forceUpdate' is undefined)
```

I'm using reaction-development-platform. I tried with both Safari and Chrome.

**Comment by loan-laux** [comment]
@ilovesourcecode The recent fixes are available on the `release-next-v3.0.0-beta.6` branch for now. They'll be merged to trunk soon. To use them at this stage, you'll need to run these commands from your `reaction-admin` directory:

```
git pull
git checkout release-next-v3.0.0-beta.6
docker stop <reaction-admin-container-name>
cd ../
make start
```

Keep an eye on PR #248 for status on this next beta version.

**Comment by ghost** [comment]
@loan-laux I get the following error when I run `make start`:

```
ERROR: manifest for reactioncommerce/admin:3.0.0-beta.6 not found: manifest unknown: manifest unknown
```

**Comment by loan-laux** [comment]
@ilovesourcecode Are you running `reaction-admin` in dev mode? If not, run `make dev-link-reaction-admin` from the root of your project, and start over.

**Comment by ghost** [comment]
@loan-laux I finally have the latest version, but it appears it's just as broken.

When I click on 'Create product', nothing happens, except I get the following errors in the console:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
Unhandled Promise Rejection: Error: Network error: Response not successful: Received status code 400
```

**Comment by loan-laux** [comment]
@ilovesourcecode Do you also have the latest version of the API? Also, can you try logging out from the admin interface and then back in?

**Comment by ghost** [comment]
@loan-laux I'm using v3.4.0. Logging out and logging back in didn't help.

I wrote the previous comment when I still didn't have a shop. After I created a shop and then tried to add a product, I got a different error:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
```

It now also takes me to an empty page where I can't do anything.

<img width="902" alt="Screen Shot 2020-04-06 at 13 22 23" src="https://user-images.githubusercontent.com/53138747/78553558-c1d19c80-7809-11ea-9395-fca10268babe.png">

**Comment by ghost** [comment]
It finally works. I went into `config.mk` and all `docker-compose.yml` files and changed the version number for everything to `trunk`.

**Comment by loan-laux** [comment]
@serdarejepov, can you or a core team member like @spencern @manueldelreal close this issue as it's been resolved?
