### ISSUE TITLE
LocalizationSettingsForm could not be saved

### ISSUE THREAD

**Issue by redscare** [reactioncommerce/reaction-admin#245]
[Product editor fixes PR](https://github.com/reactioncommerce/reaction-admin/pull/240) has a bug, which does not allow a user to save the form if defaultParcelSize is not set.

In imports/plugins/core/i18n/client/components/LocalizationSettingsForm.js:L101-104 there is an attempt to access shop.defaultParcelSize.weight|height|length|width wich causes "trying to access weight of undefined" when defaultParcelSize is not set.

**Comment by loan-laux** [comment]
@redscare This should be fixed with [beta 6 of reaction-admin](https://github.com/reactioncommerce/reaction-admin/pull/248). Can you change Git branches and confirm? Doesn't occur on my end anymore.

**Comment by willopez** [comment]
@redscare can you please confirm that this is still an issue on beta6?
